/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTarefasRouteImport } from './routes/_authenticated/tarefas'
import { Route as AuthenticatedRegrasComissionamentoRouteImport } from './routes/_authenticated/regras-comissionamento'
import { Route as AuthenticatedProdutividadeRouteImport } from './routes/_authenticated/produtividade'
import { Route as AuthenticatedPlanejamentoRouteImport } from './routes/_authenticated/planejamento'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedLeadsRouteImport } from './routes/_authenticated/leads'
import { Route as AuthenticatedHistoricoRouteImport } from './routes/_authenticated/historico'
import { Route as AuthenticatedEquipeRouteImport } from './routes/_authenticated/equipe'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedContestacoesRouteImport } from './routes/_authenticated/contestacoes'
import { Route as AuthenticatedVendasIndexRouteImport } from './routes/_authenticated/vendas/index'
import { Route as AuthenticatedVendasNovaRouteImport } from './routes/_authenticated/vendas/nova'
import { Route as AuthenticatedVendasIdRouteImport } from './routes/_authenticated/vendas/$id'
import { Route as ApiPublicTelegramServiceEventsRouteImport } from './routes/api/public/telegram-service/events'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTarefasRoute = AuthenticatedTarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRegrasComissionamentoRoute =
  AuthenticatedRegrasComissionamentoRouteImport.update({
    id: '/regras-comissionamento',
    path: '/regras-comissionamento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProdutividadeRoute =
  AuthenticatedProdutividadeRouteImport.update({
    id: '/produtividade',
    path: '/produtividade',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlanejamentoRoute =
  AuthenticatedPlanejamentoRouteImport.update({
    id: '/planejamento',
    path: '/planejamento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeadsRoute = AuthenticatedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoricoRoute = AuthenticatedHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEquipeRoute = AuthenticatedEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContestacoesRoute =
  AuthenticatedContestacoesRouteImport.update({
    id: '/contestacoes',
    path: '/contestacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVendasIndexRoute =
  AuthenticatedVendasIndexRouteImport.update({
    id: '/vendas/',
    path: '/vendas/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVendasNovaRoute = AuthenticatedVendasNovaRouteImport.update({
  id: '/vendas/nova',
  path: '/vendas/nova',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVendasIdRoute = AuthenticatedVendasIdRouteImport.update({
  id: '/vendas/$id',
  path: '/vendas/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicTelegramServiceEventsRoute =
  ApiPublicTelegramServiceEventsRouteImport.update({
    id: '/api/public/telegram-service/events',
    path: '/api/public/telegram-service/events',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contestacoes': typeof AuthenticatedContestacoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/planejamento': typeof AuthenticatedPlanejamentoRoute
  '/produtividade': typeof AuthenticatedProdutividadeRoute
  '/regras-comissionamento': typeof AuthenticatedRegrasComissionamentoRoute
  '/tarefas': typeof AuthenticatedTarefasRoute
  '/vendas/$id': typeof AuthenticatedVendasIdRoute
  '/vendas/nova': typeof AuthenticatedVendasNovaRoute
  '/vendas/': typeof AuthenticatedVendasIndexRoute
  '/api/public/telegram-service/events': typeof ApiPublicTelegramServiceEventsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contestacoes': typeof AuthenticatedContestacoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/planejamento': typeof AuthenticatedPlanejamentoRoute
  '/produtividade': typeof AuthenticatedProdutividadeRoute
  '/regras-comissionamento': typeof AuthenticatedRegrasComissionamentoRoute
  '/tarefas': typeof AuthenticatedTarefasRoute
  '/vendas/$id': typeof AuthenticatedVendasIdRoute
  '/vendas/nova': typeof AuthenticatedVendasNovaRoute
  '/vendas': typeof AuthenticatedVendasIndexRoute
  '/api/public/telegram-service/events': typeof ApiPublicTelegramServiceEventsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/contestacoes': typeof AuthenticatedContestacoesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/equipe': typeof AuthenticatedEquipeRoute
  '/_authenticated/historico': typeof AuthenticatedHistoricoRoute
  '/_authenticated/leads': typeof AuthenticatedLeadsRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/planejamento': typeof AuthenticatedPlanejamentoRoute
  '/_authenticated/produtividade': typeof AuthenticatedProdutividadeRoute
  '/_authenticated/regras-comissionamento': typeof AuthenticatedRegrasComissionamentoRoute
  '/_authenticated/tarefas': typeof AuthenticatedTarefasRoute
  '/_authenticated/vendas/$id': typeof AuthenticatedVendasIdRoute
  '/_authenticated/vendas/nova': typeof AuthenticatedVendasNovaRoute
  '/_authenticated/vendas/': typeof AuthenticatedVendasIndexRoute
  '/api/public/telegram-service/events': typeof ApiPublicTelegramServiceEventsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/contestacoes'
    | '/dashboard'
    | '/equipe'
    | '/historico'
    | '/leads'
    | '/perfil'
    | '/planejamento'
    | '/produtividade'
    | '/regras-comissionamento'
    | '/tarefas'
    | '/vendas/$id'
    | '/vendas/nova'
    | '/vendas/'
    | '/api/public/telegram-service/events'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contestacoes'
    | '/dashboard'
    | '/equipe'
    | '/historico'
    | '/leads'
    | '/perfil'
    | '/planejamento'
    | '/produtividade'
    | '/regras-comissionamento'
    | '/tarefas'
    | '/vendas/$id'
    | '/vendas/nova'
    | '/vendas'
    | '/api/public/telegram-service/events'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/contestacoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/equipe'
    | '/_authenticated/historico'
    | '/_authenticated/leads'
    | '/_authenticated/perfil'
    | '/_authenticated/planejamento'
    | '/_authenticated/produtividade'
    | '/_authenticated/regras-comissionamento'
    | '/_authenticated/tarefas'
    | '/_authenticated/vendas/$id'
    | '/_authenticated/vendas/nova'
    | '/_authenticated/vendas/'
    | '/api/public/telegram-service/events'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicTelegramServiceEventsRoute: typeof ApiPublicTelegramServiceEventsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tarefas': {
      id: '/_authenticated/tarefas'
      path: '/tarefas'
      fullPath: '/tarefas'
      preLoaderRoute: typeof AuthenticatedTarefasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/regras-comissionamento': {
      id: '/_authenticated/regras-comissionamento'
      path: '/regras-comissionamento'
      fullPath: '/regras-comissionamento'
      preLoaderRoute: typeof AuthenticatedRegrasComissionamentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/produtividade': {
      id: '/_authenticated/produtividade'
      path: '/produtividade'
      fullPath: '/produtividade'
      preLoaderRoute: typeof AuthenticatedProdutividadeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planejamento': {
      id: '/_authenticated/planejamento'
      path: '/planejamento'
      fullPath: '/planejamento'
      preLoaderRoute: typeof AuthenticatedPlanejamentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads': {
      id: '/_authenticated/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthenticatedLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historico': {
      id: '/_authenticated/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof AuthenticatedHistoricoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipe': {
      id: '/_authenticated/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof AuthenticatedEquipeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contestacoes': {
      id: '/_authenticated/contestacoes'
      path: '/contestacoes'
      fullPath: '/contestacoes'
      preLoaderRoute: typeof AuthenticatedContestacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendas/': {
      id: '/_authenticated/vendas/'
      path: '/vendas'
      fullPath: '/vendas/'
      preLoaderRoute: typeof AuthenticatedVendasIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendas/nova': {
      id: '/_authenticated/vendas/nova'
      path: '/vendas/nova'
      fullPath: '/vendas/nova'
      preLoaderRoute: typeof AuthenticatedVendasNovaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendas/$id': {
      id: '/_authenticated/vendas/$id'
      path: '/vendas/$id'
      fullPath: '/vendas/$id'
      preLoaderRoute: typeof AuthenticatedVendasIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/telegram-service/events': {
      id: '/api/public/telegram-service/events'
      path: '/api/public/telegram-service/events'
      fullPath: '/api/public/telegram-service/events'
      preLoaderRoute: typeof ApiPublicTelegramServiceEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedContestacoesRoute: typeof AuthenticatedContestacoesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEquipeRoute: typeof AuthenticatedEquipeRoute
  AuthenticatedHistoricoRoute: typeof AuthenticatedHistoricoRoute
  AuthenticatedLeadsRoute: typeof AuthenticatedLeadsRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedPlanejamentoRoute: typeof AuthenticatedPlanejamentoRoute
  AuthenticatedProdutividadeRoute: typeof AuthenticatedProdutividadeRoute
  AuthenticatedRegrasComissionamentoRoute: typeof AuthenticatedRegrasComissionamentoRoute
  AuthenticatedTarefasRoute: typeof AuthenticatedTarefasRoute
  AuthenticatedVendasIdRoute: typeof AuthenticatedVendasIdRoute
  AuthenticatedVendasNovaRoute: typeof AuthenticatedVendasNovaRoute
  AuthenticatedVendasIndexRoute: typeof AuthenticatedVendasIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedContestacoesRoute: AuthenticatedContestacoesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEquipeRoute: AuthenticatedEquipeRoute,
  AuthenticatedHistoricoRoute: AuthenticatedHistoricoRoute,
  AuthenticatedLeadsRoute: AuthenticatedLeadsRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedPlanejamentoRoute: AuthenticatedPlanejamentoRoute,
  AuthenticatedProdutividadeRoute: AuthenticatedProdutividadeRoute,
  AuthenticatedRegrasComissionamentoRoute:
    AuthenticatedRegrasComissionamentoRoute,
  AuthenticatedTarefasRoute: AuthenticatedTarefasRoute,
  AuthenticatedVendasIdRoute: AuthenticatedVendasIdRoute,
  AuthenticatedVendasNovaRoute: AuthenticatedVendasNovaRoute,
  AuthenticatedVendasIndexRoute: AuthenticatedVendasIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicTelegramServiceEventsRoute: ApiPublicTelegramServiceEventsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
