/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRegrasComissionamentoRouteImport } from './routes/_authenticated/regras-comissionamento'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedLeadsRouteImport } from './routes/_authenticated/leads'
import { Route as AuthenticatedEquipeRouteImport } from './routes/_authenticated/equipe'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedVendasIndexRouteImport } from './routes/_authenticated/vendas/index'
import { Route as AuthenticatedVendasNovaRouteImport } from './routes/_authenticated/vendas/nova'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRegrasComissionamentoRoute =
  AuthenticatedRegrasComissionamentoRouteImport.update({
    id: '/regras-comissionamento',
    path: '/regras-comissionamento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeadsRoute = AuthenticatedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEquipeRoute = AuthenticatedEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVendasIndexRoute =
  AuthenticatedVendasIndexRouteImport.update({
    id: '/vendas/',
    path: '/vendas/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVendasNovaRoute = AuthenticatedVendasNovaRouteImport.update({
  id: '/vendas/nova',
  path: '/vendas/nova',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/regras-comissionamento': typeof AuthenticatedRegrasComissionamentoRoute
  '/vendas/nova': typeof AuthenticatedVendasNovaRoute
  '/vendas/': typeof AuthenticatedVendasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/regras-comissionamento': typeof AuthenticatedRegrasComissionamentoRoute
  '/vendas/nova': typeof AuthenticatedVendasNovaRoute
  '/vendas': typeof AuthenticatedVendasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/equipe': typeof AuthenticatedEquipeRoute
  '/_authenticated/leads': typeof AuthenticatedLeadsRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/regras-comissionamento': typeof AuthenticatedRegrasComissionamentoRoute
  '/_authenticated/vendas/nova': typeof AuthenticatedVendasNovaRoute
  '/_authenticated/vendas/': typeof AuthenticatedVendasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/equipe'
    | '/leads'
    | '/perfil'
    | '/regras-comissionamento'
    | '/vendas/nova'
    | '/vendas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/equipe'
    | '/leads'
    | '/perfil'
    | '/regras-comissionamento'
    | '/vendas/nova'
    | '/vendas'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/equipe'
    | '/_authenticated/leads'
    | '/_authenticated/perfil'
    | '/_authenticated/regras-comissionamento'
    | '/_authenticated/vendas/nova'
    | '/_authenticated/vendas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/regras-comissionamento': {
      id: '/_authenticated/regras-comissionamento'
      path: '/regras-comissionamento'
      fullPath: '/regras-comissionamento'
      preLoaderRoute: typeof AuthenticatedRegrasComissionamentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads': {
      id: '/_authenticated/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthenticatedLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipe': {
      id: '/_authenticated/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof AuthenticatedEquipeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendas/': {
      id: '/_authenticated/vendas/'
      path: '/vendas'
      fullPath: '/vendas/'
      preLoaderRoute: typeof AuthenticatedVendasIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendas/nova': {
      id: '/_authenticated/vendas/nova'
      path: '/vendas/nova'
      fullPath: '/vendas/nova'
      preLoaderRoute: typeof AuthenticatedVendasNovaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEquipeRoute: typeof AuthenticatedEquipeRoute
  AuthenticatedLeadsRoute: typeof AuthenticatedLeadsRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedRegrasComissionamentoRoute: typeof AuthenticatedRegrasComissionamentoRoute
  AuthenticatedVendasNovaRoute: typeof AuthenticatedVendasNovaRoute
  AuthenticatedVendasIndexRoute: typeof AuthenticatedVendasIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEquipeRoute: AuthenticatedEquipeRoute,
  AuthenticatedLeadsRoute: AuthenticatedLeadsRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedRegrasComissionamentoRoute:
    AuthenticatedRegrasComissionamentoRoute,
  AuthenticatedVendasNovaRoute: AuthenticatedVendasNovaRoute,
  AuthenticatedVendasIndexRoute: AuthenticatedVendasIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
